name: Run Papermill Notebook

on:
  push:
    branches: [ master ]  # ✅ Use 'master' since that's your branch
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: self-hosted  # ✅ Ensure your self-hosted runner is configured

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Removed setup-python since it's not compatible with your self-hosted Debian 11 runner

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install papermill google-cloud-storage

      - name: Run Papermill script
        run: |
          python3 notebook_PM.py
