name: Run Papermill Notebook

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd && ls -R

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install papermill google-cloud-storage

      - name: Run Papermill script
        run: |
          python3 notebook_PM.py

      - name: Upload executed notebook
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebooks
          path: executed_notebooks/
